on: ["push", "pull_request"]

name: Test 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install SSH server
      run: sudo apt-get update && sudo apt-get install -y openssh-server

    - name: Start SSH server
      run: sudo service ssh start

    - name: npm install
      run: npm install
        
    - name: npm test
      run: npm test

    - name: Coveralls
      uses: coverallsapp/github-action@v2