on:
  pull_request:
    branches:
      - master
    paths:
      - '**.js'
      - '**.json'

name: Test 

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install Dependencies
      run: npm install

    - name: Run ESLint
      run: npm run eslint index.js

    - name: Setup SSH server for tests
      run: |
        sudo apt-get update && sudo apt-get install -y openssh-server
        sudo service ssh start
        sudo useradd -m -p $(openssl passwd -1 vagrant) vagrant

    - name: Run Tests with Coverage
      run: npm run coverage
    
    - name: Check Coverage
      run: npm run check-coverage
    

  coveralls:
    name: Coveralls
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH server for tests
      run: |
        sudo apt-get update && sudo apt-get install -y openssh-server
        sudo service ssh start
        sudo useradd -m -p $(openssl passwd -1 vagrant) vagrant
        
    - name: npm install
      run: |
        npm install
        npm run coverage
        npm run report-coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v2
